Añadido una página inicial para el módulo de autenticación
Full-Tortuga/decide-full-tortuga-autenticacion pull request #40
Opened 2021-12-29 13:42 UTC by josrompoz1

Si accedemos a /authentication/welcome encontramos una vista inicial para el módulo de autenticación. Desde esta vista podremos acceder a las diferentes formas de login implementadas y al registro de usuario. También, si ya hemos iniciado sesión nos dejará cerrarla. Por último, veremos un apartado Methods que explica, a modo de README, los incrementos implementados para el proyecto y un apartado About Us. En el apartado explicativo de la API de usuarios, tenemos un enlace que redirige a esta API.

2022-01-03 16:46 UTC, marsamber reviewed
A la hora de ejecutarse los tests automáticamente, se da el siguiente error:

```
Run run: cd decide;coverage run --branch --source=. ./manage.py test authentication --keepdb; coverage xml;
/home/runner/work/_temp/8714ac46-0ccc-46a0-a604-9fd25c246352.sh: line 1: run:: command not found
Error: Process completed with exit code 127.

```

2022-01-03 18:33 UTC, pabgonmon2 approved these changes
Aprobado

2022-01-03 18:45 UTC, pabgonmon2 requested changes
Debes solucionar el error que salta en la integración continua. Yo lo he solucionado hacpiendo merge de "master" a tu rama y pusheando, ya que en master se encuentran actualizado el heroku.yml.

2022-01-04 12:30 UTC, pabgonmon2 approved these changes
Corregido

2022-01-04 12:30 UTC, merged